### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Jelly9912** [deathcrow999/ItemEnchantment#1]
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] [19:04:20] [Server thread/WARNING]: Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] [19:04:20] [Server thread/INFO]: Loading pocketmine.yml...
[Server] [19:04:20] [Server thread/INFO]: Loading server properties...
[Server] [19:04:20] [Server thread/INFO]: Selected English (eng) as the base language
[Server] [19:04:20] [Server thread/INFO]: Starting Minecraft: PE server version v0.12.1 alpha
[Server] [19:04:20] [Server thread/INFO]: Opening server on 0.0.0.0:19132
[Server] [19:04:20] [Server thread/INFO]: This server is running PocketMine-MP version 1.6dev-28 "[REDACTED]" (API 1.13.0)
[Server] [19:04:20] [Server thread/INFO]: PocketMine-MP is distributed under the LGPL License
[Server] [19:04:21] [Server thread/INFO]: Loading DevTools v1.10.0
[Server] [19:04:21] [Server thread/INFO]: Loading ZipPluginLoader v1.1.2
[Server] [19:04:21] [Server thread/INFO]: Enabling DevTools v1.10.0
[Server] [19:04:21] [Server thread/INFO]: [DevTools] Registered folder plugin loader
[Server] [19:04:21] [Server thread/INFO]: Enabling ZipPluginLoader v1.1.2
[Server] [19:04:21] [Server thread/INFO]: [ZipPluginLoader] Loading zip plugin PlayerStats v1.0.0
[Server] 
[Server] Parse error: syntax error, unexpected '}' in myzip:///storage/emulated/0/PocketMine/plugins/ItemEnchantment-master.zip#ItemEnchantment-master/src/LiveWireTech/ItemEnchantment/Main.php on line 21
[Server] [19:04:21] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[Server] [19:04:21] [Server thread/EMERGENCY]: Please upload the "/storage/emulated/0/PocketMine/CrashDump_Thu_Sep_17-19.04.21-UTC_2015.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[Server] [19:04:22] [Server thread/INFO]: Disabling DevTools v1.10.0
[Server] [19:04:22] [Server thread/INFO]: Disabling ZipPluginLoader v1.1.2

**Comment by deathcrow999** [comment]
Yes i noticed this i just fixed it

**Comment by Jelly9912** [comment]
When this will be fixed ? :smiley:

**Comment by deathcrow999** [comment]
I fixed the plugin crashing problem all the syntax is correct now

**Comment by Jelly9912** [comment]
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] [19:20:47] [Server thread/WARNING]: Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] [19:20:47] [Server thread/INFO]: Loading pocketmine.yml...
[Server] [19:20:47] [Server thread/INFO]: Loading server properties...
[Server] [19:20:47] [Server thread/INFO]: Selected English (eng) as the base language
[Server] [19:20:47] [Server thread/INFO]: Starting Minecraft: PE server version v0.12.1 alpha
[Server] [19:20:47] [Server thread/INFO]: Opening server on 0.0.0.0:19132
[Server] [19:20:47] [Server thread/INFO]: This server is running PocketMine-MP version 1.6dev-28 "[REDACTED]" (API 1.13.0)
[Server] [19:20:47] [Server thread/INFO]: PocketMine-MP is distributed under the LGPL License
[Server] [19:20:48] [Server thread/INFO]: Loading DevTools v1.10.0
[Server] [19:20:48] [Server thread/INFO]: Loading ZipPluginLoader v1.1.2
[Server] [19:20:48] [Server thread/INFO]: Enabling DevTools v1.10.0
[Server] [19:20:48] [Server thread/INFO]: [DevTools] Registered folder plugin loader
[Server] [19:20:48] [Server thread/INFO]: Enabling ZipPluginLoader v1.1.2
[Server] [19:20:48] [Server thread/INFO]: [ZipPluginLoader] Loading zip plugin ItemEnchantment v1.0.0
[Server] [19:20:48] [Server thread/CRITICAL]: ClassNotFoundException: "Class LiveWireTech\ItemEnchantment\ItemEnchantment not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
[Server] [19:20:48] [Server thread/INFO]: Disabling ZipPluginLoader v1.1.2
[Server] [19:20:48] [Server thread/INFO]: Enabling ZipPluginLoader v1.1.2
[Server] [19:20:48] [Server thread/INFO]: [ZipPluginLoader] Loading zip plugin ItemEnchantment v1.0.0
[Server] [19:20:48] [Server thread/CRITICAL]: ClassNotFoundException: "Class LiveWireTech\ItemEnchantment\ItemEnchantment not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
[Server] [19:20:48] [Server thread/INFO]: Disabling ZipPluginLoader v1.1.2
[Server] [19:20:49] [Server thread/INFO]: Preparing level "world"
[Server] [19:20:49] [Server thread/INFO]: Starting GS4 status listener
[Server] [19:20:49] [Server thread/INFO]: Setting query port to 19132
[Server] [19:20:49] [Server thread/INFO]: Query running on 0.0.0.0:19132
[Server] [19:20:49] [Server thread/INFO]: Default game type: Survival Mode
[Server] [19:20:49] [Server thread/INFO]: Done (7.997s)! For help, type "help" or "?"

I think it's not good ;c

**Comment by deathcrow999** [comment]
Sorry i switched main file from Main to ItemEnchantment but forgot to change file name...i fixed the issue

**Comment by Jelly9912** [comment]
I see :laughing:  
How many items i can enchant ?

**Comment by deathcrow999** [comment]
Havent finished yet just change items in config

**Comment by Jelly9912** [comment]
What are the id for other enchants ?

**Comment by deathcrow999** [comment]
You can find a list here
http://www.planetminecraft.com/blog/minecraft-enchantment-id-list/
